### ISSUE TITLE
bug: tests in the npm package

### ISSUE THREAD

**Issue by ruscon** [rvagg/bl#106]
please, remove them

**Comment by rvagg** [comment]
no

**Comment by ruscon** [comment]
why ?

**Comment by rvagg** [comment]
The tests are a part of this library, in the same way the docs are, they ship together in a snapshot at points in time we call a "release".
I don't strip tests from any of my releases unless there's particularly large fixtures. If you have a problem with dependency bloat, start removing dependencies, the problem is not because packages have tests in them, it's because people are using far too many dependencies.

**Comment by ruscon** [comment]
> The tests are a part of this library, in the same way, the docs are

Your point of view is interesting, but there are many questions.
1. Why are you writing the documentation then if you have tests? You can write the documentation in one line: "see tests"
2. According to your logic, you need to use fewer dependencies, but you yourself use 3 npm packages in dependencies, which in turn use dependencies too. If each of these packages will store tests, don't you think that would be overkill?
