### ISSUE TITLE
TypeError: bl.pipe is not a function!

### ISSUE THREAD

**Issue by laduke** [rvagg/bl#77]
Hi!
I'm probably just tired and doing something goofy

```js
var { BufferList } = require('bl')
var bl = BufferList()

bl.append('hello')
bl.append(' world')
bl.append('\n')

bl.pipe(
  process.stdout,
  { end: false }
)
```
(one of the readme examples ^)

```
~/s/doot ❯❯❯ node -v                                                        ⏎
v10.16.0
~/s/doot ❯❯❯ node index.js
/Users/travis/src/doot/index.js:9
bl.pipe(
   ^

TypeError: bl.pipe is not a function
    at Object.<anonymous> (/Users/travis/src/doot/index.js:9:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
~/s/doot ❯❯❯ npm ls bl                                                      ⏎
/Users/travis/src/doot
└── bl@4.0.0
```

edit:
Ah, Just a doc thing 
It should be 
`const { BufferListStream } = require('bl')` or
`const BufferList  = require('bl')`
not `var { BufferList } = require('bl')`

**Comment by mcollina** [comment]
Yes, we didn't update the docs! Would you mind sending a PR?

**Comment by rvagg** [comment]
@laduke it's the distinction between `BufferList` and `BufferListStream` that's missing here. The readme has this example but is using `BufferList` when it should be using `BufferListStream`. This comes from the previous version that was the only export: `const BufferList = require('bl')` (no destructuring `{}`), that still works and if you used that construct your example would work. I think we're just trying to get people to be explicit in which one they pull out.

**Comment by laduke** [comment]
thanks! 
I think part of my confusion, as someone looking at this module for the first time, was both classes have `append`, `duplicate`, etc... methods. Does BufferListStream have all the methods + .pipe?

**Comment by rvagg** [comment]
@laduke yes, this change was very recent in fact. Until the latest release it was all integrated into a single thing. Now you have an option to omit the streaming bit; this is helpful for browser packaging where you may not want to pull in the stream dependencies which are quite large.

`BufferList` is the base, `BufferListStream` just adds the streaming bits and turns a `BufferList` into a stream. Functionality is otherwise the same.

I get your confusion though, maybe since you have fresh eyes you could consider the README and suggest where we can clarify this distinction?

**Comment by rvagg** [comment]
mm, that's actually a tricky one because many people aren't coming here for something that's a "Stream" and making invoking the verbose name will be a distraction from the functionality. Probably the best improvement for now will be a clear explanation near the top about the distinction between the two things.

I'm still just using `const bl = require('bl')` everywhere personally and I like the simplicity of this. That's `BufferListStream`. But I'm also a fan of explicitness and my use of `bl` is probably just me being a cermudgen.
